### ISSUE TITLE
No compilation

### ISSUE THREAD

**Issue by tab00** [ControlCplusControlV/hardhat-Yul#3]
I added `require("@tovarishfin/hardhat-yul")` in hardhat.config.js and put the .yul file into the contracts directory.

After running `yarn hardhat compile` it says "Nothing to compile" and there's no artifact file under artifacts\contracts.

How can I get it to work?

**Comment by tab00** [comment]
The problem was because Windows paths use backslash, and `glob` expects forward slash. So change https://github.com/ControlCplusControlV/hardhat-Yul/blob/fbe813147f12577a8f9151138afea4f7b6c2e3ea/src/compilation.ts#L65 
to:
```js
const yulFiles = glob.sync(path.join(paths.sources, "**", "*.yul").split(path.sep).join("/"));
```

Do similarly for https://github.com/ControlCplusControlV/hardhat-Yul/blob/fbe813147f12577a8f9151138afea4f7b6c2e3ea/src/compilation.ts#L72

**Comment by ControlCplusControlV** [comment]
Ty for the fix, would you like to make a PR to fix this or should I address it?

**Comment by tab00** [comment]
I think it'd be faster if you make those small changes.

**Comment by ControlCplusControlV** [comment]
Ok, will push

**Comment by ControlCplusControlV** [comment]
https://github.com/ControlCplusControlV/hardhat-Yul/commit/7f0e29f2304e7cda257d3a54539e0a6a82b82104 should be fixed now

**Comment by tab00** [comment]
Thanks for the quick fix, is it on npm?

Should we install the @tovarishfin/hardhat-yul or @controlcpluscontrolv/hardhat-yul node package?

Your README says to install @tovarishfin/hardhat-yul.

**Comment by ControlCplusControlV** [comment]
Oh yeah his plugin is the most up to date, I will publish a new version of mine later today though, this isn't really maintained anymore but can push with a new fix later tonight

**Comment by tab00** [comment]
> his plugin is the most up to date

Github says his is 3 commits behind yours though.



> I will publish a new version of mine later today

That's great, thanks a lot.

**Comment by tab00** [comment]
How's the npm update going?

**Comment by ControlCplusControlV** [comment]
@controlcpluscontrolv/hardhat-yul@3.1.0

**Comment by tab00** [comment]
I added the package to my project and got "Error: Cannot find module '" ... "\node_modules\@controlcpluscontrolv\hardhat-yul\dist\index.js'. Please verify that the package.json has a valid "main" entry"

I think you need to run `tsc --build` so that the dist directory is created in the package files.

**Comment by tab00** [comment]
I assume you're busy so don't worry about it anymore, I've found a fork that works. Thank you for your efforts.

**Comment by ControlCplusControlV** [comment]
Oh sorry, yeah I've been busy and I don't do much to maintain this anymore, sorry for the inconvience
